wiki-main/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/", views.search, name="search"),
    path("create/", views.create, name="create"),

]

wiki-main/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki-main/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki-main/encyclopedia/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse

from . import util

class NewEntryForm(forms.Form):
    title = forms.CharField(label="New Title")
    content = forms.CharField(label="Adding Content")

entries = util.list_entries()

def index(request):

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "entry": util.get_entry(title)
    })

def search(request):
    newEntriesList = []
    if request.method == "GET":
        title = request.GET.get('q')
        if title in entries :
            return render(request, "encyclopedia/entry.html", {
            "title": title,
            "entry": util.get_entry(title)
            })
        else:
            for searchItem in entries:
                if title in searchItem:
                    newEntriesList.append(searchItem),
            return render(request, "encyclopedia/index.html", {
                "entries": newEntriesList
            })

def create(request):
    if request.method == "POST":
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            newEntry = util.save_entry(title, content)
            if newEntry:
                entries.append(newEntry)
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))
            else:
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=[None]))
        else:
            return render(request, "encyclopedia/create.html", {
                "form": form
            })

    return render(request, "encyclopedia/create.html", {
            "form": NewEntryForm()
    }) 
    

wiki-main/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia - {{ title }}
{% endblock %}

{% block body %}

    {% if not entry %}
        Wikipedia does not have an article with this exact name. For more details visit our home page.
    {% else %}
        {{ entry }}
    {% endif %} 

{% endblock %}

wiki-main/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'encyclopedia:entry' entry.title %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki-main/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index'%}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create'%}">Create New Page</a>
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>